### ISSUE TITLE
Failure of Espresso test-suite with `x and y nan location mismatch`

### ISSUE THREAD

**Issue by laraPPr** [EESSI/test-suite#190]
We have seen the following error when running on a local optimised build of Espresso on a skylake cluster at Ghent University. The nodes are running on RHEL9 operating system.
```
Executing sanity checks...

Traceback (most recent call last):
  File "/kyukon/scratch/gent/461/vsc46128/EESSI/test-suite/stage/skitty/skitty/default/EESSI_ESPRESSO_P3M_IONIC_CRYSTALS_e0bb4712/madelung.py", line 115, in <module>
    np.testing.assert_allclose(energy, ref_energy, atol=atol_energy, rtol=rtol_energy)
  File "/apps/gent/RHEL9/skylake-ib/software/SciPy-bundle/2023.11-gfbf-2023b/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 1504, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/apps/gent/RHEL9/skylake-ib/software/Python/3.11.5-GCCcore-13.2.0/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/apps/gent/RHEL9/skylake-ib/software/SciPy-bundle/2023.11-gfbf-2023b/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 718, in assert_array_compare
    flagged = func_assert_same_pos(x, y, func=isnan, hasval='nan')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/gent/RHEL9/skylake-ib/software/SciPy-bundle/2023.11-gfbf-2023b/lib/python3.11/site-packages/numpy/testing/_private/utils.py", line 688, in func_assert_same_pos
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=5e-06, atol=1e-12

x and y nan location mismatch:
x: array(nan)
y: array(-1.747565)
```

**Comment by jngrad** [comment]
I can now confirm there is a bug in how ESPResSo handles the matrix operations in the grid influence function. ESPResSo expects the Fourier space to be rotated and transposed (pencil decomposition), but sometimes FFTW selects a more efficient decomposition without rotation and we end up using the wrong matrix indices. The P3M algorithm then reads data out-of-bounds, without triggering a segmentation fault. I'm not sure why this bug only surfaced on Zen4 and Zen5.

Our efforts in the last 4 weeks to correct the original FFT code were unsuccessful. espressomd/espresso#5017 introduces a check to discard incompatible FFT decompositions during tuning. Backporting this workaround to ESPResSo 4.2.2 also proved unsuccessful.

USTUTT is actively working on replacing the original FFT code by a new implementation based on [heFFTe](https://icl.utk.edu/fft/) that doesn't involve matrix rotations and is expected to be part of the next release of ESPResSo. We therefore cannot allocate more resources to this bug report and recommend the ReFrame team to skip the failing benchmarks on the affected architectures until the new ESPResSo release becomes available.
